#!/usr/bin/env bash
#
# Connect the owner's Hyperliquid wallet to PICC's CCXT ordering rail.
# Walks the human through: (1) funding the wallet, (2) creating an API wallet
# with view+trade (NO withdrawal) permissions, (3) writing the credentials into
# apps/dashboard/.env, (4) a READ-ONLY proof that PICC can see the wallet and
# price a spot pair — no order is placed anywhere in this wizard.
# Generated by the /wizard skill. Ephemeral: built for one run, not committed.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE="apps/dashboard/.env"   # run from the repo root; the server loads this at boot

banner "Hyperliquid wallet → PICC (CCXT ordering rail)"

# ── Stage 1: fund the wallet ──────────────────────────────────────────────
stage "Fund: deposit USDC from Arbitrum"
say "PICC signs with an API wallet; the funds live in your MAIN Hyperliquid account."
say "First we put at least $10 USDC in it (Hyperliquid's minimum deposit is 5 USDC;"
say "below that is NOT credited)."
printf '\n'
say "You need, before starting:"
step "USDC on Arbitrum One (not Ethereum, not USDT — ONLY native USDC on Arbitrum)."
step "A little ETH on Arbitrum for gas (the deposit is an Arbitrum transaction)."
printf '\n'
if ! confirm "Do you already have both (USDC + a few dollars of ETH) on Arbitrum?"; then
  say "Prepare first, then re-run or continue here:"
  step "If you hold USDC on a CEX: withdraw USDC choosing the Arbitrum network."
  step "If you hold USDC elsewhere: bridge to Arbitrum first (bridge.arbitrum.io)."
  step "Move a small amount of ETH to Arbitrum for gas (~$2-3 is plenty)."
  pause "Once funded on Arbitrum, press Enter to continue"
fi
printf '\n'
say "Now the deposit (2-5 minutes):"
open_url "https://app.hyperliquid.xyz/"
note "Only ever use app.hyperliquid.xyz / app.hyperliquid-testnet.xyz — bookmark it, no lookalikes."
step "Connect the wallet you will trade with (or log in with your email account)."
step "Click Deposit → USDC → Arbitrum network."
step "Enter at least 10 USDC, review the modal's CURRENT minimum/limits, confirm."
step "Approve the USDC spending allowance (first time only), then confirm the deposit."
step "Wait — deposits typically credit in under a minute."
step "Check Portfolio: you should see the USDC balance."
pause "Deposit landed and visible in your Hyperliquid Portfolio? (should show ≥ 10 USDC)"
printf '\n'
say "Capture your MAIN wallet address (the account this deposit landed in)."
note "This is public on-chain data — NOT a secret. ccxt needs it as the account address;"
note "the API wallet's private key (next stage) is the only secret PICC signs with."
ask PICC_CCXT_WALLETADDRESS_HYPERLIQUID "Paste your main wallet address (0x...):"
if [[ ! "$PICC_CCXT_WALLETADDRESS_HYPERLIQUID" =~ ^0x[0-9a-fA-F]{40}$ ]]; then
  warn "doesn't look like a 0x + 40 hex-char address — double-check before continuing"
  confirm "Continue anyway?" || { pause "Paste it again next time; stopping here"; exit 1; }
fi
write_env PICC_CCXT_WALLETADDRESS_HYPERLIQUID "$PICC_CCXT_WALLETADDRESS_HYPERLIQUID"

# ── Stage 2: create the API wallet ────────────────────────────────────────
stage "API wallet: view + trade, NO withdrawal"
say "Hyperliquid has no API keys — you authorize a separate 'API wallet' keypair"
say "that can read + trade on your account but CANNOT withdraw. PICC signs with it."
printf '\n'
open_url "https://app.hyperliquid.xyz/API"
step "Open Settings → API (or use the /API page just opened)."
step "Click Generate (name it something like 'picc')."
step "Permissions toggles: enable Reading AND Trading."
warn "Leave Withdrawals DISABLED — a leaked key can then only trade, never drain."
step "Generate → the PRIVATE KEY is shown ONCE. Copy it now."
pause "Private key copied (it will never be shown again)?"
printf '\n'
note "If you lose it: revoke this API wallet and generate a new one — never reuse."
ask_secret PICC_CCXT_PRIVATEKEY_HYPERLIQUID "Paste the API wallet private key (0x...):"
if [[ ! "$PICC_CCXT_PRIVATEKEY_HYPERLIQUID" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
  warn "doesn't look like a 0x + 64 hex-char private key — double-check before continuing"
  confirm "Continue anyway?" || { pause "Paste it again next time; stopping here"; exit 1; }
fi
write_env PICC_CCXT_PRIVATEKEY_HYPERLIQUID "$PICC_CCXT_PRIVATEKEY_HYPERLIQUID"

# ── Stage 3: .env health check ────────────────────────────────────────────
stage "Credentials: saved and safe"
say "Both values are now written to $ENV_FILE (gitignored, server-side only,"
say "never logged, never sent to the browser)."
printf '\n'
if [[ -f "$ENV_FILE" ]] && grep -q "^PICC_CCXT_WALLETADDRESS_HYPERLIQUID=0x" "$ENV_FILE" && \
   grep -q "^PICC_CCXT_PRIVATEKEY_HYPERLIQUID=0x" "$ENV_FILE"; then
  say "✓ Hyperliquid credentials present in .env."
  note "  PICC_CCXT_WALLETADDRESS_HYPERLIQUID=0x$(grep '^PICC_CCXT_WALLETADDRESS_HYPERLIQUID=' "$ENV_FILE" | cut -d= -f2 | cut -c1-10)..."
  pk=$(grep '^PICC_CCXT_PRIVATEKEY_HYPERLIQUID=' "$ENV_FILE" | cut -d= -f2 | cut -c1-6)
  note "  PICC_CCXT_PRIVATEKEY_HYPERLIQUID=${pk}... (masked — never typed out)"
else
  warn "one or both keys missing from $ENV_FILE — re-run the earlier stages."
  confirm "Continue anyway?" || exit 1
fi
printf '\n'
say "Sandbox check for PROD:"
if grep -q "^PICC_CCXT_SANDBOX_HYPERLIQUID=1" "$ENV_FILE"; then
  warn "PICC_CCXT_SANDBOX_HYPERLIQUID=1 is set — PICC will talk to the TESTNET, not this wallet."
  confirm "Remove it so PICC uses the LIVE venue?" && grep -v "^PICC_CCXT_SANDBOX_HYPERLIQUID=1" "$ENV_FILE" > "$ENV_FILE.tmp" && mv "$ENV_FILE.tmp" "$ENV_FILE" && say "✓ removed."
else
  say "✓ no sandbox flag → PICC will use the LIVE Hyperliquid venue."
fi
pause "Press Enter to continue to the proof"

# ── Stage 4: read-only proof ──────────────────────────────────────────────
stage "Proof: PICC reads your wallet + prices a spot pair (NO order placed)"
say "PICC loads .env at BOOT — restart your dashboard so the new credentials load:"
step "Stop your dashboard process (Ctrl-C in its terminal)."
step "Start it again the way you usually do (e.g. npm run dev or npm run serve in apps/dashboard)."
pause "Server restarted?"
printf '\n'
say "Now prove the rail reads, without placing anything (propose = gate-check only):"
open_url "http://localhost:3000"
step "Open the Command Centre page → Orders (trading stream)."
step "Order form: exchange = hyperliquid, symbol = PURR/USDC."
step "side = buy; amount ≈ 50; price = the CURRENT PURR/USDC spot price from the venue"
note "  (a buy limit at/below market passes the sanity gate; we are NOT executing)."
step "Click Propose."
printf '\n'
say "A GOOD result (the rail works):"
note "  • the gate chain renders GREEN (fresh equity + fresh reference price + consent)"
note "  • the rationale shows the fresh market price from Hyperliquid"
note "  • the overview feed gains a 'trading:ccxt' row showing your ~$10 USDC equity"
printf '\n'
say "Then do NOT execute — this was the proof. Leave it proposed or kill it (there is"
say "no execution until a fresh per-action click, and the venue was never touched)."
printf '\n'
warn "If propose shows unpriced / stale feeds / balance-unobservable instead:"
note "  note the exact wording, then tell the assistant — do not retry blindly."
pause "What did the proposal show — green rail, or something honest-but-blocked?"
say "Done. Reply to the assistant that the wizard finished, and what stage 4 showed."
finish